language: generic
sudo: required
services : 
    - docker

before_install:
    - docker build -t docker.quix.it/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true docker.quix.it/docker-react npm run test